baseURL = 'https://www.tianpai.io/'
languageCode = 'en-us'
title = "Tianpai Blog"
author = 'Tianpai Z'
copyright = 'Copyright Â© 2025, Tianpai Z'
theme = 'bearIM'

enableRobotsTXT = true
# Bearblog keeps URLs simple by skipping taxonomy pages entirely.
disableKinds = ['taxonomy']
ignoreErrors = ['error-disable-taxonomy']

[permalinks]
  blog = '/:slug/'
  tags = '/blog/:slug'

[params]
  description = 'Experiments with Hugo Bear Blog.'
  favicon = 'images/favicon.png'
  images = ['images/share.png']
  title = "Tianpai's Blog"
  enablePostNavigator = true

[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
